# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170717_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=50),
        ),
    ]
